name: socketcluster_client
description: SocketCluster.io Client for Dart
version: 0.0.1
authors: 
- Paul DeMarco
- Michael Marner <michael@20papercups.net>
homepage: pauldemarco.com

dependencies:

dev_dependencies:
  test: ^0.12.0
