name: socketcluster_client
description: SocketCluster.io Client for Dart
version: 0.0.1
authors:
  - Paul DeMarco
  - Michael Marner <michael@20papercups.net>
homepage: pauldemarco.com
environment:
  # Works in Dart 2 only.
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.3.0
